version: "3.7"


######################################
# create an external network
networks:
  caddy:
    external: true

#######################################
volumes:
  nextcloud-apache2:
  nextcloud-data:
  nextcloud-config:
  nextcloud-db:
  caddy-data:


services:
#########################################################################
  # Caddy reverse proxy
  caddy:
    image: lucaslorentz/caddy-docker-proxy
    container_name: caddy_proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy-data:/data
    restart: unless-stopped

#########################################################################
      # goto /var/snap/docker/common/var-lib/volume/nextcloud-config
      # change port.conf in apache2 to 1080 and 1443 for nextcloud to run
  nextcloud-app:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud-data:/var/www/html
      - nextcloud-apache2:/etc/apache2
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nextcloud-config:/config
    environment:
      - MYSQL_PASSWORD=<your_database_password>
      - MYSQL_DATABASE=nextcloud_sql_db
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_ADMIN_USER=<NC_USERNAME>
      - NEXTCLOUD_ADMIN_PASSWORD=<YOUR_SECRET_PASSWORD>
      - NEXTCLOUD_TRUSTED_DOMAINS=www.nextcloud.<yourdomain>.com nextcloud.<yourdomain>.com https://nextcloud.<yourdomain>.com
      - OVERWRITEPROTOCOL=https
    ports:
      - 1080:1080
      - 1443:1443
    networks:
      - caddy
    depends_on:
      - nextcloud-db
    labels:
      caddy: nextcloud.<yourdomain>.com
      caddy.reverse_proxy: "{{upstreams 1080}}"  

  nextcloud-db:
    image: mariadb
    restart: unless-stopped
    container_name: mariadb-nxtcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<SQL_ROOT_PASSWORD>
      - MYSQL_PASSWORD=<SQL_USER_PASSWORD>
      - MYSQL_DATABASE=nextcloud_sql_db
      - MYSQL_USER=<SQL_USER_NAME>
    networks:
      - caddy
